### ISSUE TITLE
Critical Issues

### ISSUE THREAD

**Issue by evanhessler** [evanhessler/CrookBook#42]
Dear @MaxwellWilliams  ,

I am writing to you with utmost frustration and disappointment regarding the numerous issues with the Murder Book Organizer App that we built for LAPD. I have spent countless hours trying to fix the problems, but it seems that the app is riddled with technical bugs that require your immediate attention.

Firstly, the database schema seems to have major discrepancies, which are resulting in data loss and inconsistency. As you know, the murder book organizer app is a crucial tool for the LAPD to manage their investigations. Any errors in data can lead to inaccurate leads, jeopardizing the entire case.

Furthermore, the API endpoints are not performing optimally, which is causing the app to lag and ultimately affecting the user experience. The entire system seems to be sluggish, and the users are finding it challenging to navigate through the app.

Additionally, the app's search functionality is flawed, making it difficult for the LAPD investigators to retrieve the necessary information. The search queries are taking an eternity to process, and the results are not even accurate. This issue needs to be resolved urgently as it is directly affecting the efficiency of the investigators.

I hope you understand the gravity of the situation and take immediate action to address these critical issues. The LAPD relies on this app to solve murders and bring justice to the victims' families. It is unacceptable for them to be using an app that is not performing optimally and posing a risk to their investigations.

Please let me know when you can start working on these issues, and I hope to hear back from you soon.

**Comment by MaxwellWilliams** [comment]
@evanhessler Thank you for the feedback, as you know we continuously strive to meet the needs of the LAPD and our other users.

Data loss is a major issue which we would like to address immediately, can you point our team to an example of data loss you, or the LAPD investigators, have experienced?

Our APIs may indeed be being bogged down by excessive logic an queries, additional information on the LAPD investigator's use cases would enable us to create performant APIs which don't perform any unnecessary logic.  Would you be able to provide any insight on these particular use cases?

The same questions can be asked for the search functionality issues, are the fields being matched not what the investigators expect?  Or is the search/matching logic not returning the expected results regardless of the fields?

Again, thank you for your invaluable input.  Without feedback from our end users we are unable to build CrookBook into the platform everyone has envisioned. In the future, we can hopefully establish more regular communication to identify these issues before they become critical, and even encourage collaboration with LAPD investigators or IT staff.

**Comment by nsunga** [comment]
Closing issue. Fork the repo since the Tech Lead doesnt want to do it for Q1-Q2

Revenue estimates are down as it is.
